### ISSUE TITLE
Add documentation pages like seen with Agda

### ISSUE THREAD

**Issue by RemcoSchrijver** [agda/agda2hs#100]
Right now there is quite a lot of implicit knowledge needed for the use of agda2hs or the need to look at examples to start using agda2hs.
It would be nice to have something comparable to [the doc of agda](https://agda.readthedocs.io/en/v2.6.2.1/) on a smaller scale of course.

**Comment by jespercockx** [comment]
We now have some (basic) documentation pages at https://agda.github.io/agda2hs/introduction.html. There are definitely a lot of things missing, but I think it's better if we create new issues about adding specific things to the documentation.
