### ISSUE TITLE
Qualified imports

### ISSUE THREAD

**Issue by jespercockx** [agda/agda2hs#123]
Currently all imports that are generated by agda2hs are *unqualified*, even if the Agda source uses a qualified import. We should instead respect the user decision on whether to use a qualified or unqualified name.

Note that the current approach is actually buggy when two modules are imported qualified that export the same name.

**Comment by omelkonian** [comment]
It seems impossible? to reconstruct the import statements, as names have been resolved/disambiguated and "import ... as ..." is unobservable at this point in typechecking.

For instance, let's assume you import a module with `as`:
```agda
open import Haskell.Prelude
import Importee as A

bar : Int
bar = A.foo
{-# COMPILE AGDA2HS bar #-}
```
which we would like to translate to:
```hs
import qualified Importee as A

bar :: Int
bar = A.foo
```
But when compiling `n = A.foo :: QName` the name is actually `"Importee.foo"` and the `TCState` does not seem to have any mapping stored that witnesses the renaming to `"A"` (I've looked at most fields of the state, but to no avail).

@jespercockx  mentioned that `DisplayForm`s should provide that, but `displayForm n []` is still `"Importee.foo"`. Am I missing something?

In internal lingo, what we want is an association from `Abstract.ModuleInfo` to `Syntax.Info.ModuleInfo`, which I think should be provided upstream. @andreasabel Any idea if that's possible/desirable or have I missed something that's already there?
