### ISSUE TITLE
Incorrect compilation when variables are shadowed

### ISSUE THREAD

**Issue by flupe** [agda/agda2hs#145]
When variables are shadowed, some unexpected results are produced:

```agda
data Ok (a : Set) {@0 a : Set} : Set where
  Thing : a → Ok _
{-# COMPILE AGDA2HS Ok #-}

test : Ok Bool
test = Thing "ok"
{-# COMPILE AGDA2HS test #-}
```

```haskell
data Ok a = Thing a

test :: Ok Bool
test = Thing "ok"
```

The code we get doesn't typecheck so it's "fine" for some notion of fine, but still, the definition of `Ok` we get on the Haskell side *is* correct Haskell, and *NOT* the one we have on the Agda side.

**Comment by omelkonian** [comment]
Is shadowing really the problem here? What about this simpler example:
```agda
data Ok {@0 a : Set} : Set where
  Thing : a → Ok _
{-# COMPILE AGDA2HS Ok #-}
```
```hs
data Ok = Thing a
```
I guess the fix here is to prevent free variables of constructors/fields refer to @0-quantity types in the context of the data/record declaration. WDYT?

**Comment by jespercockx** [comment]
I agree, the shadowing is not really the problem but rather the fact that agda2hs generates unbound variables. I agree with your proposed way to fix this.

**Comment by omelkonian** [comment]
Do you know of an easy way to get all free **visible** variables of a term/type?
... since the provided `TypeChecking/Monad/Context/allFreeVars`, and in particular the `VarOcc` information, only store modality info and not visibility.
