### ISSUE TITLE
Compilation of invalid identifiers

### ISSUE THREAD

**Issue by omelkonian** [agda/agda2hs#15]
We always keep identifiers unchanged through compilation, but there is a mismatch between what is considered a valid identifier in Haskell and in Agda.

For instance, translating an Agda definition named `my-def` typechecks in Agda, but would lead to invalid Haskell code.

**Comment by UlfNorell** [comment]
Or in the worst case, _valid_ Haskell code.

Indeed, there are lots of checks missing on identifiers.
