### ISSUE TITLE
Omitted parameters of functions declared within record namespace

### ISSUE THREAD

**Issue by viktorcsimma** [agda/agda2hs#185]
As I can see, functions declared within record namespace often lose their parameters; maybe because their type is evaluated wrong.

Here is my example code:

```agda
open import Agda.Builtin.Bool

record RecordTest : Set where
  constructor MkRecord
  field
    aBool : Bool

  aBoolAsAFunction : Bool
  aBoolAsAFunction = aBool
open RecordTest public
{-# COMPILE AGDA2HS RecordTest newtype #-}

test : Bool
test = aBoolAsAFunction (MkRecord true)
{-# COMPILE AGDA2HS test #-}
```

And the output is:

```hs
module RecordTest where

newtype RecordTest = MkRecord{aBool :: Bool}

test :: Bool
test = aBoolAsAFunction
```

So the `(MkRecord true)` parameter gets omitted.

I've tried to take a look at `Record.hs`, but I think I don't understand it yet... So I would be grateful for any help:)

**Comment by jespercockx** [comment]
Your code is missing a pragma `{-# COMPILE AGDA2HS aBoolAsAFunction #-}`. But if we add this pragma the problem only gets worse:
```haskell
{-# LANGUAGE ScopedTypeVariables #-}
module Issue185 where

newtype RecordTest = MkRecord{aBool :: Bool}

aBoolAsAFunction :: forall r . Bool
aBoolAsAFunction = aBool r

test :: Bool
test = aBoolAsAFunction
```
