### ISSUE TITLE
Warnings for unrecognised identifiers

### ISSUE THREAD

**Issue by viktorcsimma** [agda/agda2hs#191]
We could add a flag which gives a warning if agda2hs founds an identifies neither defined in the current project nor rewritten by a rewrite rule. This would make purging invalid references to agda2hs-incompatible libraries (e. g. the Agda standard library) easier.

See #189 for the current state of related code.

**Comment by jespercockx** [comment]
Isn't this the same as #119?

**Comment by viktorcsimma** [comment]
Largely yes... the only difference is that the rewrite rules also have to be considered now.
