### ISSUE TITLE
Emacs mode not working since Agda 2.6.4 update

### ISSUE THREAD

**Issue by viktorcsimma** [agda/agda2hs#208]
I have already changed the version numbers in the `.el` files from `2.6.3` to `2.6.4`, but there seems to be a bigger problem.

As far as I can see, the agda2hs binary does not support `--interaction` and `--disable-backend` used together. The error message is:
```
$ agda2hs --interaction --disable-backend input.agda
Error: Unrecognized option:
--disable-backend

Run 'agda2hs --help' for help on command line options.
```
The same message is what I get when trying to open a file in Emacs. Previously, the `--disable-backend` option is what was needed to use the `--interaction` option; now they don't seem to work together.

When only trying with the `--interaction` option:
```
$ agda2hs --interaction ErasureAndIrrelevance.agda
Error: Must not specify an input file (/home/csimma/Downloads/ErasureAndIrrelevance.agda) with --interaction
Run 'agda2hs --help' for help on command line options.
```
I don't know whether there has been a change in Agda 2.6.4 in the use of `--interaction`, or there is some other problem. Do you have any ideas? Thank you in advance!

**Comment by jespercockx** [comment]
Ah, I had no idea that the `--disable-backend` option existed when I ran into https://github.com/agda/agda2hs/issues/201, so I implemented a hacky workaround to make `--interaction` work with the `agda2hs` executable. 

The error you are getting with just `--interaction` is because you should not give a file to `agda2hs` when calling it with `--interaction`.

**Comment by jespercockx** [comment]
Has there ever been a `--disable-backend` option? I can't find it anywhere, actually.

**Comment by viktorcsimma** [comment]
It got in in #198. I think the error message was something like `cannot use --interaction when running backend`; so I added an option that disabled the backend.

**Comment by jespercockx** [comment]
Yes that seems like a good idea and is essentially what I tried to implement. If you have a cleaner way to implement it that would be very welcome!
