### ISSUE TITLE
Tuple projection bug

### ISSUE THREAD

**Issue by flupe** [agda/agda2hs#215]
The following Agda code:

```agda
pair : Int × Int
pair = (1 , 2)

{-# COMPILE AGDA2HS pair #-}

test : Int
test = let (x , y) = pair in x + y

{-# COMPILE AGDA2HS test #-}
```

Gets translated into the following:

```haskell
pair :: (Int, Int)
pair = (1, 2)

test :: Int
test = fst pair + fst (snd pair)
```

Somehow, the right component has an additional `fst` that makes it incorrect.

**Comment by jespercockx** [comment]
@flupe I see you did some work on this issue, what is the current status?

**Comment by jespercockx** [comment]
Would you have time to work on this during this week? It's the only open issue with the 1.2 label at the moment.
