### ISSUE TITLE
Allow instance arguments for non-typeclass records

### ISSUE THREAD

**Issue by flupe** [agda/agda2hs#218]
Similarly to #217, instance arguments and search is often used when doing intrinsinc verification. However, the data being searched may be runtime-relevant (i.e non-erased) and not a typeclass instance.

I suggest we let `agda2hs` keep track of whether a record has been compiled to a class or a Haskell data, and allow instance arguments of the latter, as long as we turn them explicit.

One such example is `Rezz` for [resurecting erased values](https://github.com/jespercockx/agda-core/blob/main/Utils.agda#L294):

```agda
record Rezz (a : Set) (@0 x : a) : Set where
  constructor Rezzed
  field
    rezzed : a
    @0 isRezzed : y ≡ x

open Rezz public

{-# COMPILE AGDA2HS Rezz unboxed #-}
```

It gets compiled unboxed (i.e `Rezz a x` gets compiled to `a`). Yet, instance search can be used on the Agda side to avoid having to construct evidence manually.

**Comment by jespercockx** [comment]
Same comment as for #217, I think this is a sensible thing to add support for.
