### ISSUE TITLE
Disappearing qualified import

### ISSUE THREAD

**Issue by flupe** [agda/agda2hs#219]
Minimal example of a bug I encountered with qualified imports.

`A.agda`:
```agda
module A where

open import Haskell.Prelude

X : Set
X = ⊤

{-# COMPILE AGDA2HS X #-}
```

`B.agda`:
```agda
module B where

open import Haskell.Prelude

import A

X : Set
X = A.X

{-# COMPILE AGDA2HS X #-}
```

---

Compiling file `B.agda` yields:

```haskell
module B where

import A (X)

type X = X
```

`A` is not imported qualified somehow.

**Comment by flupe** [comment]
Don't know if this is intended behavior, but the current test case for qualified import does expect the qualification to disappear:

https://github.com/agda/agda2hs/blob/15314cd3fbc505ead13e48257194afd5ca171672/test/QualifiedImports.agda#L7-L15

https://github.com/agda/agda2hs/blob/15314cd3fbc505ead13e48257194afd5ca171672/test/golden/QualifiedImports.hs#L3-L12

**Comment by omelkonian** [comment]
Maybe worth looking at the "clashing-imports check":

https://github.com/agda/agda2hs/blob/master/test/Fail/ClashingImport.agda#L1-L12

(generally, the whole feature got introduced in PR #136)

This bug might suggest two possible solutions:
1. Extend the check to also account for name clashing with definitions of this module.
2. Treat `import M` in Agda as `import qualified M as M` in Haskell.

**Comment by flupe** [comment]
Gonna investigate. Personally I think your 2nd solution to be the most sensible choice.

**Comment by jespercockx** [comment]
I agree with solution 2. A non-opened import really should be translated to a qualified import in Haskell.
