### ISSUE TITLE
Functions defined with an absurd pattern get no definition in Haskell

### ISSUE THREAD

**Issue by flupe** [agda/agda2hs#223]
If a function with a single clause is defined with an absurd pattern, only the type signature gets generated in the corresponding Haskell code.

```agda
impossible : @0 ⊥ → a
impossible ()
{-# COMPILE impossible #-}
```

```haskell
impossible :: a
```

We probably should have a default clause that throws a runtime error.

**Comment by jespercockx** [comment]
The idea was that you shouldn't use absurd patterns and instead make an explicit call to the `error` function.

**Comment by flupe** [comment]
Then it should be caught and prevented by agda2hs!
