### ISSUE TITLE
Compilation of non-erased module parameters

### ISSUE THREAD

**Issue by jespercockx** [agda/agda2hs#265]
Currently `agda2hs` assumes that all non-erased module parameters are types and should be compiled to explicit `foralls`. For example:
```agda
module _ (x : Int) where
  
  foo : Int
  foo = x

{-# COMPILE AGDA2HS foo #-}
```
is compiled to
```haskell
foo :: forall x . Int
foo = x
```
We should either compile the module parameter to a regular function argument, or else throw an error that non-type module parameters are not supported.

**Comment by flupe** [comment]
With current master, this compiles to:

```haskell
foo :: Int
foo x = x
```

Still bogus, a bit less so. Investigating now.

**Comment by jespercockx** [comment]
This is fixed by https://github.com/agda/agda2hs/pull/304
