### ISSUE TITLE
Provide Sigma compiled to tuples

### ISSUE THREAD

**Issue by flupe** [agda/agda2hs#268]
```agda
record Sigma (a : Set) (b : @0 a → Set) : Set where
  constructor Pair
  field
    fst : a
    snd : b fst
{-# COMPILE AGDA2HS Sigma #-}
```

(The builtin dependent sigma type, properly annotated).

**Comment by jespercockx** [comment]
Looks good. Once we have https://github.com/agda/agda2hs/issues/105 we could make it compile to actual Haskell pairs.

**Comment by jespercockx** [comment]
See https://github.com/jespercockx/agda-core/blob/main/src/Agda/Core/Utils.agda#L14-L29
