### ISSUE TITLE
Unary operators

### ISSUE THREAD

**Issue by bwbush** [agda/agda2hs#319]
Running `agda2hs` on code like

```agda
+++_ : Nat → Nat
+++_ x = 2 * x
{-# COMPILE AGDA2HS +++_ #-}

usage : Nat
usage = +++ 5
```

reports an error

```console
Invalid name for Haskell function:  +++_
```

Is there a way to define unary operators in `agda2hs`?

Note that according to the [Haskell Wiki](https://wiki.haskell.org/Unary_operator#:~:text=Haskell%20only%20has%20one%20built,similar%20rules%20to%20infix%20operators.), "Unary operators may also be defined and used by the programmer with similar rules to infix operators."

**Comment by jespercockx** [comment]
Currently this is not supported by agda2hs, though a PR adding support for it would be welcome. (I personally didn't even know that Haskell had unary operators.)

**Comment by UlfNorell** [comment]
What does the Haskell code look like for the unary operator (I also was not aware of user-defined unary operators in Haskell)?

**Comment by jmchapman** [comment]
Hi @bwbush , what is the expected code this should compile to?
