### ISSUE TITLE
with

### ISSUE THREAD

**Issue by jmchapman** [agda/agda2hs#40]

**Comment by UlfNorell** [comment]
It's not clear that this makes sense. Remember that we're representing Haskell code in Agda, not trying to compile arbitrary Agda code to Haskell. So, the question is: what is the Haskell code that you would like to represent using a `with`?

**Comment by omelkonian** [comment]
> It's not clear that this makes sense. Remember that we're representing Haskell code in Agda, not trying to compile arbitrary Agda code to Haskell. So, the question is: what is the Haskell code that you would like to represent using a `with`?

I guess `with` clauses might be useful if we try to cover more Haskell extensions, e.g. view patterns.

**Comment by jespercockx** [comment]
I'm closing this since it is not clear what we should actually support here, feel free to open a new issue for e.g. view patterns.
