### ISSUE TITLE
deriving

### ISSUE THREAD

**Issue by jmchapman** [agda/agda2hs#42]

**Comment by UlfNorell** [comment]
Possible design:
```agda
data MyDatatype : Set where
  ...
{-# COMPILE AGDA2HS MyDatatype deriving (Show, Eq, Ord) #-}
```

**Comment by jespercockx** [comment]
Wouldn't you also want the derived instances be available on the Agda side? Which would mean you'd have to implement some tactics for automatically deriving instances in Agda.

**Comment by omelkonian** [comment]
Let's assume you have a deriving macro (I already have something [here](https://github.com/omelkonian/formal-prelude/blob/a3ff049c5d5af002efdac8b2e903e34d0ad98a6e/Prelude/Generics.agda#L185-L199), e.g. for [DecEq](https://github.com/omelkonian/formal-prelude/blob/a3ff049c5d5af002efdac8b2e903e34d0ad98a6e/Prelude/DecEq.agda#L270)).
It can be used like this:
```agda
data ℕ′ : Set where
  O : ℕ′
  S : ℕ′ → ℕ′
unquoteDecl DecEq-ℕ′ = DERIVE DecEq [ quote ℕ′ , DecEq-ℕ′ ]
```
My question is, will we be able to grab the DERIVE directive before unquoting, so as to emit Haskell deriving alongside the datatype? Does the current Agda backend infra support such a thing?

**Comment by jespercockx** [comment]
I believe it's currently not possible for a backend to determine whether a function was written using `unquoteDecl` or by hand, unfortunately. So the declaration would be translated to a hand-written instance in Haskell. Maybe that's anyway safer, since I don't see how you would guarantee that the Agda implementation of the instance corresponds to the one derived by Haskell.

**Comment by UlfNorell** [comment]
It's certainly safer to translate all code from Agda, but I think in many cases you are not super worried about getting the instance wrong and then it would be convenient to only define it on the Agda side and have it derived on the Haskell side. Whether the Agda definition is done with a macro or by hand doesn't really make a difference.

**Comment by jmchapman** [comment]
I think if one uses `deriving` in it's simplest form one should postulate the functionality in Agda (not sure how this works with instances though) following the usual guidance described in the [manual](https://agda.readthedocs.io/en/latest/language/foreign-function-interface.html#using-haskell-functions-from-agda). I think it's analogous to using code written by a third party from an external haskell module (e.g. bytetring) except here the third party is ghc.

If one actually implements `show` in Agda then it should get compiled to non-derived instance of `Show` in Haskell.

**Comment by UlfNorell** [comment]
Yes, that will be safer. By that same logic we shouldn't implement any of the Prelude functions on the Agda side, they should be postulates or compiled from the Agda definitions.

I don't think it makes a lot of sense to force the user to postulate the `show` function (say) if they want it derived on the Haskell side. How would we even go about checking that?

**Comment by jmchapman** [comment]
Ah, I see, I hadn't connected the dots. So, this `deriving` inside the area of overlap like the prelude.
