### ISSUE TITLE
Bug: Enum type operations

### ISSUE THREAD

**Issue by ioanasv** [agda/agda2hs#55]
I am trying to understand and test agda2hs and I encountered the following problem when testing operations such as succ or prev of the Enum type.

This is the method I am trying to translate to Haskell:
<img width="276" alt="Screen Shot 2021-04-22 at 11 36 26 AM" src="https://user-images.githubusercontent.com/56679711/115683714-67957200-a35f-11eb-9067-2196fc856176.png">

Which gives the following type instance error:
<img width="452" alt="Screen Shot 2021-04-22 at 11 36 54 AM" src="https://user-images.githubusercontent.com/56679711/115683780-75e38e00-a35f-11eb-9a43-981a0c50f089.png">

When debugging I noticed that checking for the maximum and minimum bounds is causing this type instance problem, and if I remove the checks, the code is compiled and translated to Haskell just fine (but the checks should be there indeed).
<img width="603" alt="Screen Shot 2021-04-22 at 11 40 25 AM" src="https://user-images.githubusercontent.com/56679711/115683982-a3c8d280-a35f-11eb-9409-30bcc4712b3f.png">

Is there any way I could solve this problem?

**Comment by omelkonian** [comment]
In case you are still puzzled about this, the problem stems from the fact that this prelude functions are partial, i.e. not well-defined on all inputs (see the discussion on issue #28). Therefore, on the Agda side, you should make sure that these cases are guaranteed to not happen, in this case that the argument to `succ` is not the maximum element.
