### ISSUE TITLE
Compiling records to Haskell single-constructor datatypes

### ISSUE THREAD

**Issue by flupe** [agda/agda2hs#59]
In Haskell it seems frequent to emulate "record types" by defining single-constructor datatypes with named fields. When defined as such, they behave much like agda's record types.

Right now, it looks like agda2hs compiles all record types into class definitions.
I was wondering whether it would make sense to let the user compile some record types to Haskell "records" as such:

```agda
record QuadTree (a : Set) : Set where
  constructor Wrapper
  field
    wrappedTree : Quadrant a
    treeLength  : Int
    treeWidth   : Int
    treeDepth   : Int
{-# COMPILE AGDA2HS record QuadTree #-}
```
into
```hs
data QuadTree a = Wrapper { wrappedTree :: Quadrant a
                          , treeLength  :: Int
                          , treeWidth   :: Int
                          , treeDepth   :: Int
                          }
```
I'd be willing to give a try at implementing this, if it is indeed a desirable feature.

**Comment by jespercockx** [comment]
I think it would even make sense to have this be the default behaviour when compiling a record, and have a keyword for compiling to a type class (`{# COMPILE AGDA2HS class ... #-}`).

**Comment by UlfNorell** [comment]
#61 was missing support for projection functions. Coming in #62.
