### ISSUE TITLE
References to patterns in case_of_λ not translated correctly

### ISSUE THREAD

**Issue by Sh-Anand** [agda/agda2hs#71]
```scanrList : (a → b → b) → b → List a → List b
scanrList f z [] = z ∷ []
scanrList f z (x ∷ xs) =
  case scanrList f z xs of λ {
    [] -> [] 
  ; qs@(q ∷ _) -> f x q ∷ qs
  }
{-# COMPILE AGDA2HS scanrList #-}
```

is incorrectly translated to

```scanrList :: (a -> b -> b) -> b -> [a] -> [b]
scanrList f z [] = [z]
scanrList f z (x : xs)
  = case scanrList f z xs of
        [] -> []
        q : _ -> f x q : (q : xs₁)
```

where qs is removed, and a non-existent variable xs₁ is generated.

**Comment by Sh-Anand** [comment]
Further experimentation has revealed that the issue only arises when `_` is used instead of using a variable.

```
scanrList f z [] = z ∷ []
scanrList f z (x ∷ xs) =
  case scanrList f z xs of λ {
    [] -> [] 
  ; qs@(q ∷ qs') -> f x q ∷ qs
  }
{-# COMPILE AGDA2HS scanrList #-}
```
gets translated to

```
scanrList f z [] = [z]
scanrList f z (x : xs)
  = case scanrList f z xs of
        [] -> []
        q : qs' -> f x q : (q : qs')
```

which at least compiles

**Comment by dxts** [comment]
I think this is a more general issue with `as-Pattern`s. agda2hs doesn't retain as-Patterns and tries to substitute them inplace, but this breaks when you use a wildcard `_` as the variable is then un-defined like in your first example.

```
delete k t@(Bin _ kx x l r) = case (compare k kx) of
  λ {
    LT → t
  ; GT → t
  ; EQ → glue l r
  }
```
```
delete k (Bin _ kx x l r) = case compare k kx of
  LT -> Bin sz kx x l r
  GT -> Bin sz kx x l r
  EQ -> glue l r
```

**Comment by jespercockx** [comment]
I "fixed" this issue for now by throwing an error when Agda2Hs tries to compile an as-pattern. Ideally we would actually allow them, but then we would have to reverse the substitution that Agda did in the internal syntax (or change Agda so it keeps track of let-bindings and as-bindings explicitly).
