### ISSUE TITLE
Support for compiling `case_of_ λ` with inspect idiom to Haskell code.

### ISSUE THREAD

**Issue by dxts** [agda/agda2hs#74]
I would like to submit a feature request for adding support for converting a `case_of_ λ` function of the following form to a `case` clause in Haskell.

```
case'_of_ : {A B : Set} -> (a : A) -> ((a' : A) -> {eq : a ≡ a'} -> B) -> B
case' x of f = f x {refl}
```

I used such a construct a few times while trying to refine a pre-condition proof into smaller cases for their respective recursive calls, would be great if it could be converted to the respective `case` clause in Haskell.

```
find :: Ord k => k -> Map k a -> a
find  !_ Tip = error "Map.!: given key is not an element in the map"
find k (Bin _ kx x l r) = case compare k kx of
      LT -> go k l
      GT -> go k r
      EQ -> x
```
```
find : {k a : Set} {{_ : Ord k}} → (key : k) (map : Map k a) → {key ∈ map} → a
find key Tip = error "Map.!: given key is not an element in the map"
find key t@(Bin sz kx x l r) {prf} = case' compare key kx of
  λ {
    LT {eq} -> find key l {∈L sz key kx x l r eq prf}
  ; GT {eq} -> find key r {∈R sz key kx x l r eq prf}
  ; EQ {eq} -> x
  }
```

**Comment by jespercockx** [comment]
It would be nice if we could provide a number of pragmas for compiling a given Agda function to a built-in Haskell constructs such as `if/then/else` and `case/of`, and perhaps even allow *several* functions to be compiled to the same Haskell construct.
