### ISSUE TITLE
Detecting use of `FlexibleContexts` extension

### ISSUE THREAD

**Issue by dxts** [agda/agda2hs#75]
When adding instance parameters to functions which are not of the type `<class> <type-variable(s)>` . For example
```
delete : {k a : Set} ⦃ _ : Ord k ⦄ ⦃ _ : Eq (Map k a) ⦄ → k → Map k a → Map k a

delete :: Ord k => Eq (Map k a) => k -> Map k a -> Map k a
```
The `FlexibleContexts` extension is required to allow the class context `Eq (Map k a) =>`, is there some way to automatically detect the use of this extension or to mark explicitly that this extension should be added on translation.

**Comment by UlfNorell** [comment]
You should be able to add

```agda
{-# FOREIGN AGDA2HS {-# LANGUAGE FlexibleContexts #-} #-}
```
to your file.

**Comment by dxts** [comment]
Ah didn't know I could put pragmas inside the Foreign pragma. 
It works! Thanks
