### ISSUE TITLE
Agda-2.6.2

### ISSUE THREAD

**Issue by UlfNorell** [agda/agda2hs#79]
Two issues:
- The internals have changed in 2.6.2. The most annoying change being no `Data` instance for `Definition`
- `Agda.Builtin.Reflection` has changed, breaking the `Haskell.Prim.Absurd` tactic.

The first issue is easily solved with some `#if` statements. See #78. Not sure what the best way to handle the second issue is. We could
- drop 2.6.1 support
- split the lib in `lib-2.6.1` and `lib-2.6.2` (lots of duplication and not so nice for maintenance)
- ??

**Comment by jespercockx** [comment]
What is the reason for continuing to support 2.6.1? Unless there's a strong reason that I can't think of at the moment I'd just drop support for it.

**Comment by UlfNorell** [comment]
Yes, that's probably the reasonable thing to do. If it was just a couple of `#if`s that was needed it would have been nice to support both.

@jmchapman would upgrading to 2.6.2 be a problem at IOHK?

**Comment by jmchapman** [comment]
I asked and we don't expect that to be a problem.
