### ISSUE TITLE
Do not erase implicit arguments unless they are marked @0

### ISSUE THREAD

**Issue by jespercockx** [agda/agda2hs#88]
Currently agda2hs erases all implicit arguments in the translation to Haskell code, which may change the semantics of the program. For example, consider the following program:
```agda
open import Haskell.Prelude
open import Haskell.Prim.Bool

data Vec (a : Set) : {n : Nat} → Set where
  Nil  : Vec a {zero}
  Cons : {n : Nat} → a → Vec a {n} → Vec a {suc n}
{-# COMPILE AGDA2HS Vec #-}

sneaky : {n : Nat} → Vec Bool {n} → Int
sneaky     Nil            = 0
sneaky {1} (Cons True xs) = 1
sneaky     (Cons x xs)    = 2
{-# COMPILE AGDA2HS sneaky #-}

result = sneaky (Cons true (Cons false Nil))
{-# COMPILE AGDA2HS result #-}
```
Agda2Hs translates this to the following:
```haskell
data Vec a = Nil
           | Cons a (Vec a)

sneaky :: Vec Bool -> Int
sneaky Nil = 0
sneaky (Cons True xs) = 1
sneaky (Cons x xs) = 2

result :: Int
result = sneaky (Cons True (Cons False Nil))
```

When evaluating `result` in Agda, the result is `2`, however after erasing implicit arguments the result of evaluating `result` in Haskell is `1`. Worse, one could prove a property of an Agda program that fails to hold for the translated Haskell program.

There is a relatively simple way to solve this problem, which is to only erase arguments if they are marked as erased with `@0`. This way Agda's type system guarantees that the run-time value of an expression does not depend on parts of the expression that are erased. However, this is a quite fundamental change in the current design of Agda2Hs, so it should be considered carefully.

One other advantage of making this change is that it becomes really super simple to explain what parts of the Agda source code are erased: precisely those marked with @0. This is in contrast to the current situation where implicit arguments are erased, irrelevant arguments are erased, and instance arguments are erased sometimes except when they are translated to a constraint instead.

If we decide to go through with this change there's one choice to be made of whether to translate non-erased implicit arguments to explicit arguments in Haskell, or to disallow them completely. My vote would go to the latter option since it is the least likely to lead to confusion or mistakes.

**Comment by jespercockx** [comment]
One more thought: if we decide on this approach, we could also require that top-level definitions that should not be compiled to Haskell must be annotated with `@0`, which would remove the need for having a `{-# COMPILE AGDA2HS ... #-}` pragma for every definition that you want to compile.

**Comment by omelkonian** [comment]
+1 for this, much more intuitive and well behaved!

**Comment by omelkonian** [comment]
> which would remove the need for having a `{-# COMPILE AGDA2HS ... #-}` pragma for every definition that you want to compile.

Since we rely on these pragmas to pass additional information to the backend (classes, deriving, etc...), it seems awkward to have only part of the definitions like that. Maybe stick to always having a pragma, to also be consistent with the other major backends?

**Comment by jespercockx** [comment]
Yeah after thinking about it some more perhaps getting rid of the pragmas isn't such a good idea after all. In particular, it would require the ability to add `@0` annotations to data and record types, which is currently not possible.

**Comment by jespercockx** [comment]
After experimenting a bit with this change I've come to the unfortunate conclusion that Agda is currently not quite ready to fully move to erasure annotations for Agda2Hs. In particular, there are two problems with the way type classes are implemented:

1. When opening a record type with `open R {{...}}` syntax, the parameters are not marked as erased in the types of the projections (see https://github.com/agda/agda/issues/5769)
2. The parameters are not marked as erased either in the types of definitions inside a record type, no matter how you open the record module (see https://github.com/agda/agda/issues/5769#issuecomment-1027039109)

Workarounds for both problems are possible but require major changes to the Agda code that make it much less nice to write and look much less like the generated Haskell code, so I gave up on trying those. So unless someone (perhaps @UlfNorell ) thinks of a very clever workaround, we're stuck with the current approach until these two issues are fixed.

**Comment by jespercockx** [comment]
So actually the second issue is actually really easy to fix, the only problem is that it breaks some existing code. So I tried adding it under a flag `--erase-record-parameters` instead: https://github.com/agda/agda/pull/5771/. As a nice bonus, enabling this flag actually also solves the first issue (or rather, it is not an issue anymore in the first place). So one option would be to go through with the change to Agda2Hs proposed here, but for the moment change it to install from an unreleased version of Agda (until a version of Agda with the `--erase-record-parameters` is released). I could even make a branch of the latest release of 2.6.2.1 and backport this flag to it, so that users of Agda2Hs wouldn't have to worry about unreleased changes to Agda. What do you think of this option?

**Comment by jespercockx** [comment]
The `--erase-record-parameters` has been merged into the master branch of Agda, and there have been no negative remarks about this proposal. We also ran five student project with the version of Agda2Hs that relies on explicit erasure annotations, so I believe it is safe to say that this is the way to go forward with Agda2Hs.
