### ISSUE TITLE
Sized coinductive datatypes with `Thunk`

### ISSUE THREAD

**Issue by flupe** [agda/agda2hs#99]
@RemcoSchrijver has been experimenting with infinite data structures defined using coinductive records, but the lack of support for copatterns #98 has proven to be quite annoying. And it doesn't look straightforward to implement.

Rather, maybe we should think about adding stdlib's [sized `Thunk` coinductive record](https://github.com/agda/agda-stdlib/blob/master/src/Codata/Sized/Thunk.agda) in our own prelude. This way, we could define infinite structures "very" naturally:

```agda
data Colist (a : Set) (i : Size) : Set where
  Nil  : Colist a i
  Cons : a -> Thunk (Colist A) i -> Colist A i

repeat : ∀ {@0 a i} → a → Colist a i
repeat x = Cons x λ where .force → repeat x
```

and have `Thunk` disappear entirely during translation:

```haskell
data Colist a = Nil | Cons a (Colist A)

repeat :: a -> Colist a
repeat x = Cons x (repeat x)
```

We most likely can treat `Size` like we treat `Set` and erase them always.
Feedback welcome.

**Comment by RemcoSchrijver** [comment]
At the moment translation of repeat happens as follows and we get the same problem seen in #98 so the result we get with the following agda code:

```agda
data CoList (a : Set) (@0 i : Size) : Set where
  Nil  : CoList a i
  _:::_ : a → Thunk (CoList a) i → CoList a i
{-# COMPILE AGDA2HS CoList #-}

repeatCoList : {a : Set} {@0 i : Size} → a → CoList a i
repeatCoList x = x ::: (λ where .force → repeatCoList x)
{-# COMPILE AGDA2HS repeatCoList #-}
```

Gives the following Haskell translation:

```haskell
data CoList a = Nil
              | (:::) a (Thunk (CoList a))

repeatCoList :: a -> CoList a
repeatCoList x
  = x :::
      \case
          Data.Thunk.Thunk.force -> repeatCoList x
```

I am going to try to work around the lambda notation, because I suspect this might be the offender because force is translated properly in the function like drop for example.

**Comment by jespercockx** [comment]
There is now a `Thunk` type in `Haskell.Prim.Thunk` that you can use to define coinductive datatypes. Please give it a try!
